<a href="https://colab.research.google.com/github/Agtna/AI-2025/blob/main/matriks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Operasi Matematika menggunakan python


In [ ]:
x = min(5, 10, 25)
y = max(6, 12, 18)
print(x)
print(y)


5
18


In [ ]:
x = abs(-7.25)
print(x)


7.25


In [ ]:
import math
x = math.pow(4, 3)
print(x)

64.0


In [ ]:
import math
x = math.sqrt(64)
print(x)

8.0


In [ ]:
import math
x = math.ceil(1.4)
y = math.floor(1.4)
print(x)
print(y)

2
1


In [ ]:
import math
x = math.pi
print(x)


3.141592653589793


In [ ]:
import numpy as np
A = np.array([[80, 30, 25],
[50, 20, 10]])
B = np.array([[30, 60, 15],
[10, 30, 30]])

hasil = A + B
print(hasil)

[[110  90  40]
 [ 60  50  40]]


In [ ]:
import numpy as np
A = np.array([10, 20, 15])
B = np.array([16, 67, 35])

hasil = np.dot(A, B)
print(hasil)

2025


In [ ]:
import numpy as np
A = np.array([10, 20, 15])
B = np.array([16, 67, 35])

Hasil = np.cross(A, B)
print(hasil)

2025


In [ ]:
import math
# Trigonometri
x = math.radians(30)  # Konversi 30 derajat ke radian
print("sin(30°):", math.sin(x))
print("cos(60°):", math.cos(x))
print("tan(30°):", math.tan(x))

sin(30°): 0.49999999999999994
cos(60°): 0.8660254037844387
tan(30°): 0.5773502691896257


In [ ]:
# Logaritma
print("log(10):", math.log(10))  # Logaritma natural (basis e)
print("log10(100):", math.log10(100))  # Logaritma basis 10

log(10): 2.302585092994046
log10(100): 2.0


In [ ]:
# Konversi sudut
print("180 radian ke derajat:", math.degrees(math.pi))

180 radian ke derajat: 180.0


In [ ]:
# Jarak Euclidean
p1 = (3, 4)
p2 = (0, 0)
print("Jarak Euclidean antara", p1, "dan", p2, ":", math.dist(p1, p2))

Jarak Euclidean antara (3, 4) dan (0, 0) : 5.0


In [ ]:
# Faktorial
print("5! =", math.factorial(5))

5! = 120


In [ ]:
# Modulus
print("10.5 % 3 =", math.fmod(10.5, 3))

10.5 % 3 = 1.5


In [ ]:
# Pengecekan NaN
print("Apakah NaN?:", math.isnan(float('nan')))

Apakah NaN?: True


In [ ]:
# Fungsi Gamma
print("Gamma(5):", math.gamma(5))  # Sama dengan (5-1)!

Gamma(5): 24.0


In [ ]:
# Permutasi
print("Permutasi 5P3:", math.perm(5, 3))


Permutasi 5P3: 60


# Penugasan

In [ ]:
import numpy as np

# Definisi matriks
A = np.array([[3, 1], [2, 0]])
B = np.array([[2, 1], [1, -1]])
C = np.array([[-1, 1, 2], [2, 0, -1]])

# Perkalian matriks
AxB = np.dot(A, B)
BxC = np.dot(B, C)

# Menampilkan hasil
print("A x B:")
print(AxB)

print("B x C:")
print(BxC)


A x B:
[[7 2]
 [4 2]]
B x C:
[[ 0  2  3]
 [-3  1  3]]


In [ ]:
# Menghitung faktorial
faktorial_6 = math.factorial(6)
print("6!:", faktorial_6)


6!: 720


In [ ]:
# Menghitung 8! / 5!
hasil = math.factorial(8) / math.factorial(5)
print("8! / 5!:", hasil)


8! / 5!: 336.0


In [ ]:
# Definisi vektor
vec_A = np.array([5, 3, 7])
vec_B = np.array([12, -3, 1])

# Panjang masing-masing vektor
length_A = np.linalg.norm(vec_A)
length_B = np.linalg.norm(vec_B)
print("Panjang Vektor A:", length_A)
print("Panjang Vektor B:", length_B)

# Perkalian titik (dot product)
dot_product = np.dot(vec_A, vec_B)
print("A . B:", dot_product)

# Perkalian silang (cross product)
cross_product = np.cross(vec_A, vec_B)
print("A x B:")
print(cross_product)


Panjang Vektor A: 9.1104335791443
Panjang Vektor B: 12.409673645990857
A . B: 58
A x B:
[ 24  79 -51]
